// Region context only. These entries never claim live capacity, credentials,
// completed work, instant availability, or a specific outcome.
const sharedFaqs = (place) => [
  [`Is ${place} inside the confirmed service area?`, `It is inside Lake & Pine's planning corridor. Exact coverage depends on the property, program, travel, qualified crew, and requested window.`],
  ["Can I reserve a date from this page?", "No. Submit preferred dates and an alternate. An operator confirms a feasible window only after scope and capacity review."],
  ["What details should I send first?", "Program, general location, property scale, condition, priorities, and timing. Do not send access codes, payment data, or sensitive site information in the public form."],
];

export const serviceAreas = [
  {
    slug: "coeur-dalene",
    city: "Coeur d'Alene",
    state: "ID",
    seo_phrase: "Premium property cleaning planning in Coeur d'Alene",
    headline: "Interior Care Planning for Exceptional Coeur d'Alene Properties",
    intro: "Private residences, owner handoffs, lake and marine interiors, and presentation-led business spaces around Coeur d'Alene require different access, finish, duration, and crew plans. Lake & Pine reviews each request before confirming fit.",
    neighborhoods: ["Sanders Beach", "Fort Grounds", "Riverstone", "Garden District", "Tubbs Hill corridor", "Downtown"],
    highlights: [
      { title: "Private Estate Care", body: "Large and finish-sensitive residences are scoped around rooms, materials, access, cadence, and the owner's readiness goal." },
      { title: "Construction Handoff", body: "Completed construction and renovation scopes are gated by trade completion, utilities, safe access, and walkthrough timing." },
      { title: "Marine Interior Care", body: "Cabins and owner spaces are reviewed as interior work only, with vessel access and material restrictions documented first." },
    ],
    faqs: sharedFaqs("Coeur d'Alene"),
    lat: 47.6777,
    lng: -116.7805,
    sort: 1,
  },
  {
    slug: "spokane",
    city: "Spokane",
    state: "WA",
    seo_phrase: "Premium estate and commercial cleaning planning in Spokane",
    headline: "Reviewed Estate, Construction, and Commercial Care in Spokane",
    intro: "Spokane's historic residences, exceptional homes, construction projects, professional offices, studios, and showrooms benefit from a written scope and finish-aware crew plan. Availability is confirmed property by property.",
    neighborhoods: ["South Hill", "Rockwood", "Manito", "Kendall Yards", "Browne's Addition", "Perry District"],
    highlights: [
      { title: "Finish-Aware Residences", body: "Historic materials, millwork, stone, and owner product restrictions are documented before service." },
      { title: "Owner Handoffs", body: "Construction final-clean and walkthrough scopes are sequenced only after the site passes readiness review." },
      { title: "Select Commercial Care", body: "Professional, presentation-led spaces are considered after security, occupant, frequency, and operating-window review." },
    ],
    faqs: sharedFaqs("Spokane"),
    lat: 47.6588,
    lng: -117.426,
    sort: 2,
  },
  {
    slug: "post-falls",
    city: "Post Falls",
    state: "ID",
    seo_phrase: "Construction handoff and estate cleaning planning in Post Falls",
    headline: "Construction Handoff and Private Property Care in Post Falls",
    intro: "New construction, renovation handoffs, large residences, and select business environments in Post Falls are reviewed for scale, readiness, specialty surfaces, access, and crew time before a proposal is prepared.",
    neighborhoods: ["Falls Park", "Riverbend", "Treaty Rock", "Prairie Falls", "Corbin Park", "Black Bay"],
    highlights: [
      { title: "Final-Clean Readiness", body: "Active trades, hazardous debris, remediation, and missing utilities are excluded from the assumed final-clean scope." },
      { title: "Arrival Preparation", body: "Owner arrival work is planned around a defined interior outcome rather than an anonymous checklist." },
      { title: "Route Discipline", body: "Duration and travel buffers are protected before any schedule is confirmed." },
    ],
    faqs: sharedFaqs("Post Falls"),
    lat: 47.7169,
    lng: -116.9516,
    sort: 3,
  },
  {
    slug: "hayden",
    city: "Hayden",
    state: "ID",
    seo_phrase: "Private estate and lake interior care planning in Hayden",
    headline: "Private Estate and Lake Interior Care Planning in Hayden",
    intro: "Hayden and Hayden Lake requests are evaluated for property scale, finish sensitivity, seasonal access, route fit, and the qualified crew required. A city listing is not a blanket capacity promise.",
    neighborhoods: ["Hayden Lake", "Honeysuckle", "Prairie Avenue corridor", "Hayden Meadows", "Avondale"],
    highlights: [
      { title: "Seasonal Estate Care", body: "Arrival, departure, initial reset, and recurring plans can be documented against the same property brief." },
      { title: "Lake Access Planning", body: "Parking, gates, docks, and material restrictions are coordinated privately after initial fit review." },
      { title: "Quality Closeout", body: "The operating plan includes an agreed checklist, exception notes, and operator review." },
    ],
    faqs: sharedFaqs("Hayden"),
    lat: 47.7623,
    lng: -116.7866,
    sort: 4,
  },
  {
    slug: "liberty-lake",
    city: "Liberty Lake",
    state: "WA",
    seo_phrase: "Premium residence and commercial cleaning planning in Liberty Lake",
    headline: "Reviewed Property Care for Liberty Lake Residences and Businesses",
    intro: "Large residences, professional offices, studios, and presentation-led spaces in Liberty Lake are considered for recurring or project care after an operator reviews scope, security, timing, travel, and team capacity.",
    neighborhoods: ["Liberty Lake Village", "Pavillion Park", "Rocky Hill", "Meadowwood", "Liberty Creek"],
    highlights: [
      { title: "Durable Property Plans", body: "Recurring care is based on a maintained room, finish, product, and access record." },
      { title: "Business Operating Windows", body: "Occupancy, alarms, keys, and service windows are resolved before a commercial schedule is confirmed." },
      { title: "Capacity Before Cadence", body: "A requested weekly or monthly cadence is approved only when the route and qualified team can support it." },
    ],
    faqs: sharedFaqs("Liberty Lake"),
    lat: 47.6668,
    lng: -117.1105,
    sort: 5,
  },
  {
    slug: "spokane-valley",
    city: "Spokane Valley",
    state: "WA",
    seo_phrase: "Construction and commercial cleaning planning in Spokane Valley",
    headline: "Construction Handoff and Select Commercial Care in Spokane Valley",
    intro: "Lake & Pine reviews completed construction, renovation, model-home, office, studio, showroom, and exceptional-residence requests in Spokane Valley. Rapid-turn rental work is not the operating focus.",
    neighborhoods: ["Millwood", "Painted Hills", "Ponderosa", "Greenacres", "Dishman"],
    highlights: [
      { title: "Construction-to-Owner Wedge", body: "A qualified final clean can lead into owner arrival preparation and a durable estate-care plan." },
      { title: "Commercial Fit Review", body: "Regulated, industrial, medical, laboratory, food-production, and hazardous sanitation work is outside the assumed scope." },
      { title: "Explainable Crew Choice", body: "Program experience, skills, availability, time off, travel, and workload are evaluated before a crew is proposed." },
    ],
    faqs: sharedFaqs("Spokane Valley"),
    lat: 47.6733,
    lng: -117.2394,
    sort: 6,
  },
  {
    slug: "rathdrum",
    city: "Rathdrum",
    state: "ID",
    seo_phrase: "Premium property cleaning planning in Rathdrum",
    headline: "Route-Reviewed Property Care in Rathdrum",
    intro: "Rathdrum properties can involve acreage, longer travel, new construction, exceptional residences, and seasonal access. Lake & Pine confirms the route, duration, skills, and practical service window before accepting work.",
    neighborhoods: ["Timberlake", "Twin Lakes", "Westwood Terrace", "Ross Point", "Silver Lake corridor"],
    highlights: [
      { title: "Travel-Aware Scheduling", body: "Drive time and travel buffers are part of the capacity decision, not invisible pressure on the crew." },
      { title: "New-Build Handoffs", body: "Final-clean work begins only after the site meets the agreed readiness criteria." },
      { title: "Honest Coverage", body: "If a property or timing request cannot be responsibly supported, the operator offers another window or declines before confirmation." },
    ],
    faqs: sharedFaqs("Rathdrum"),
    lat: 47.8121,
    lng: -116.8977,
    sort: 7,
  },
];

// Testimonials remain empty until verified customer evidence exists.
export const placeholderReviews = [];
